#!/usr/bin/env python3

import sys
import math

x1 = float(sys.argv[1])
y1 = float(sys.argv[2])
z1 = float(sys.argv[3])
x2 = float(sys.argv[4])
y2 = float(sys.argv[5])
z2 = float(sys.argv[6])
n = int(sys.argv[7])
vx = x2 - x1
vy = y2	- y1
vz = z2	- z1
xn = x2 + vx * n
yn = y2	+ vy * n
zn = z2	+ vz * n
angle = ()

print("The velocity vector of the ball is:\n({:.2f}, {:.2f}, {:.2f})".format(vx, vy, vz))
print("At time t + {}, ball coordinates will be:\n({:.2f}, {:.2f}, {:.2f})".format(n, xn, yn, zn))
if z2 >= 0 and zn <= 0:
    angle = 0
    print("The incidence angle is:\n{:.2f} degrees".format(angle))
if z2 < 0 and zn > 0:
    angle = 1
    print("The incidence angle is:\n{:.2f} degrees".format(angle))
else:
    print("The ball won't reach the bat")
